/* Slide content map. Each side-by-side slide names its screenshot and the gap
   checker item numbers whose requirement lands on that screen. Item text is
   read from gap.json so the deck and the workbook cannot drift apart. */
module.exports={
 /* Items that are not missing a data source but a feature. Disposal is not in
    the system yet and Physical Records comes after Utilization, so these
    cannot be built now for a reason the client controls, not one we failed at.
    Kept apart from the red items on purpose: red needs an answer from them,
    this needs a release to ship. */
 later:{
  '1 Bank-wide Oversight':{ns:[55,56,57,58,59,60,61],rel:'Disposal release'},
  '2 Department Insights':{ns:[73,74,75,76,77,78],rel:'Disposal release'},
  '5 Retention and Disposal':{ns:[26],rel:'Disposal release'},
  '6 Records and Archive Holdings':{ns:[25,26],rel:'Physical Records release'},
 },
 order:[
  {key:'bw',sheet:'1 Bank-wide Oversight',name:'Bank-wide Oversight',
   q:'How is EDRMS being used across the whole bank?',
   slides:[
    {img:'bw-01.png',t:'The ten headline figures',items:[1,10],
     say:['Every figure the client drew on slide 34 is on this one strip.',
          'The two grey tiles are doors, not numbers: they open the other dashboards.',
          'Two labels changed. I will explain why on the questions slide.']},
    {img:'bw-drill-sites.png',t:'Sites, department by department',items:[11,20],
     say:['Click any figure on the strip above and the table underneath changes.',
          'Every department name opens that department’s own dashboard.',
          'The four indicators on the right are sites created, deleted, archived and gone quiet.']},
    {img:'bw-drill-sov.png',t:'Project sites, sovereign and nonsovereign',items:[21,23],
     say:['The client asked for these as two separate lists. Both are here.',
          'Any project row opens Project Insights for that project.',
          'The bottom row is the facility total, because their own slide ends the list with “Etc.”']},
    {img:'bw-drill-users.png',t:'Users',items:[24,33],
     say:['We can see who has actually used EDRMS. We cannot see who they are.',
          'Six of the ten things asked for here need something from you.',
          'This is the biggest single gap in the whole report.']},
    {img:'bw-drill-docs.png',t:'Documents',items:[34,39],
     say:['Document counts and storage size are solid and come from real data.',
          'What is missing is history: we can show today, not the trend.',
          '“Per division” appears again here. It appears on six screens in total.']},
    {img:'bw-drill-rec.png',t:'Records declared',items:[40,45],
     say:['This is the number the whole programme is judged on.',
          'The declaration rate compares records declared against documents held.',
          'Departments with zero declarations are flagged so they can be chased.']},
    {img:'bw-drill-phys.png',t:'Physical counterparts',items:[46,50],
     say:['A physical counterpart is a declared record that also exists on paper.',
          'This is the bridge between this report and what RAC holds in its rooms.',
          'What we cannot show is whether the paper actually reached RAC.']},
    {img:'bw-drill-disp.png',t:'Records due for disposal',items:[51,61],
     say:['We can show what is due, and when. That part is solid.',
          'We cannot show what happened next, because nothing records an outcome.',
          'Seven of the eleven items here are waiting on that one gap.']},
    {img:'bw-04.png',t:'Trends and comparisons',items:[62,65],
     say:['The curve is cumulative, so the last point is the running total to date.',
          'You can set any date range and the two figures beneath update.',
          'The comparison panel above ranks departments on three named ratios.']},
   ],
   asks:[
    {q:'Who is staff, who is a consultant, and who is a contractor?',
     b:'The report can see that 1,200 people used EDRMS. It cannot see what kind of person each one is, so we cannot split any user figure three ways as you asked.',
     n:'Is there a list somewhere — HR, or a directory — that says which category each person falls into? Even a monthly export would do.'},
    {q:'Which department does each person belong to?',
     b:'Same problem. We can count people, but we cannot say a person belongs to SARD rather than HRD, so “users per department” cannot be built.',
     n:'Where is that held today, and could we read it?'},
    {q:'Who has completed EDRMS training?',
     b:'You asked for a training completion figure on two screens. Nothing we can reach records training.',
     n:'Who keeps the training records, and in what form?'},
    {q:'Who joined since go-live?',
     b:'We can see activity, but not a start date, so “onboarded since go-live” cannot be counted.',
     n:'Is a joining date recorded anywhere we could match to a person?'},
    {q:'What counts as a division?',
     b:'“Per division” appears on six different screens. We can group by department today, but nothing tells us which division inside a department a site or a person belongs to.',
     n:'Is there an agreed list of divisions, and does something already tag sites or people with one?'},
    {q:'Can we keep a monthly history?',
     b:'Several of your indicators are month-on-month — new documents, storage growth, records disposed. Today we can only see the current position, not last month’s.',
     n:'This one we can solve ourselves by taking a monthly snapshot. We just need your agreement to start, because the history only builds from the day we begin.'},
    {q:'Who approves a disposal, and what did they decide?',
     b:'The report can show what is due for disposal. It cannot show approved, declined or extended, because the system has nowhere to record that decision.',
     n:'How is a disposal approved today — email, a form, a meeting? If we know where the decision lives, we can work out how to bring it in.'},
    {q:'How do we know a paper file actually reached RAC?',
     b:'We can see which records are marked as having a paper counterpart. We cannot see whether that paper was handed over.',
     n:'Does RAC record what it receives, and could we match that back to the record in EDRMS?'},
    {q:'How many people are creating documents?',
     b:'We can count documents. Counting the distinct people who created them needs a different kind of report than the one we have access to.',
     n:'This is one for us to solve, but it may need a change request. Flagging it so it is not a surprise later.'},
   ]},

  {key:'dp',sheet:'2 Department Insights',name:'Department Insights',
   q:'How is one department using EDRMS?',
   slides:[
    {img:'dp-01.png',t:'The department profile',items:[1,11],
     say:['Pick a department at the top and every figure on the screen follows it.',
          'The same seven headline figures as bank-wide, narrowed to one unit.',
          'Two things are missing from the profile: the naming convention and the go-live date.']},
    {img:'dp-drill-users.png',t:'Users and activity',items:[12,19],
     say:['Used in the last 180 days, gone quiet, never touched it — all three are here.',
          'The same user-type gap as bank-wide appears again.',
          'Training completion is asked for here too.']},
    {img:'dp-drill-sites.png',t:'This department’s sites',items:[20,30],
     say:['Every site the department owns, with its owner named.',
          'All six columns the client drew are present.',
          'This screen is complete — nothing red on it.']},
    {img:'dp-drill-visitors.png',t:'Site visitors',items:[31,44],
     say:['Page views and unique pages, per site, with quick date windows.',
          'You can also pick any month and year.',
          'What we cannot yet do is separate ADB people from outsiders.']},
    {img:'dp-drill-docs.png',t:'Documents',items:[45,51],
     say:['Counts and storage size, per site.',
          'Solid and sourced, apart from one item.',
          'Same “how many people are creating documents” question as bank-wide.']},
    {img:'dp-drill-rec.png',t:'Records declaration',items:[52,59],
     say:['Records declared, people declaring, and total declared size.',
          'Sites that have declared nothing in 180 days are flagged.',
          'Only the two per-division items are missing.']},
    {img:'dp-drill-phys.png',t:'Physical counterparts',items:[62,66],
     say:['Which sites hold records with a paper copy, and what share that is.',
          'Same handover gap as bank-wide.',
          'Note items 60 and 61 sit under this heading in the workbook.']},
    {img:'dp-drill-disp.png',t:'Disposal',items:[67,78],
     say:['Due within three, six and twelve months, all three windows.',
          'Next due date and whether there is paper alongside.',
          'Six of the twelve items wait on the same disposal-outcome gap.']},
    {img:'dp-03.png',t:'Library usage',items:[79,86],
     say:['The client drew this as six screens, one per file plan category.',
          'We have the library table. We cannot yet group libraries by category.',
          'That is the same file plan gap we will see on the next dashboard.']},
   ],
   asks:[
    {q:'What is the approved naming convention?',
     b:'You asked us to show whether sites, libraries and folders follow the approved convention. We have never been shown what the convention actually is.',
     n:'Is it written down? If we have the rule, we can check every site against it automatically.'},
    {q:'When did each department go live?',
     b:'The profile has a space for a go-live date, but nothing records one.',
     n:'Is there a rollout schedule we could use — even a spreadsheet?'},
    {q:'Who is an ADB person and who is an outside visitor?',
     b:'We can count visits to a site. We cannot tell whether the visitor was ADB staff or someone external, so the internal / external split cannot be built.',
     n:'Same underlying question as the user types on the last dashboard. One answer would unlock both.'},
    {q:'Where are access requests recorded?',
     b:'You asked how many requests for access were granted and how many were denied. Nothing we reach records either.',
     n:'When someone asks for access to a site, where does that request go, and is the outcome kept?'},
    {q:'Which libraries belong to which file plan category?',
     b:'You drew library usage as six screens, one per category. We can list the libraries; we cannot say which category each one belongs to.',
     n:'Is that mapping written down anywhere, or does it live in someone’s head?'},
    {q:'What are the programme dates?',
     b:'The deck refers to programme milestones. We have no dates to plot against.',
     n:'Can we have the agreed milestone dates, so progress can be shown against plan?'},
   ]},

  {key:'pj',sheet:'3 Project Insights',name:'Project Insights',
   q:'Are project sites being kept up to recordkeeping standards?',
   slides:[
    {img:'pj-01.png',t:'The project list',items:[1,1],extra:[20,21],
     say:['Sovereign and nonsovereign, switched with the picker.',
          'Click any project to open its profile below.',
          'The totals reconcile: named projects sit inside the facility total, which sits inside bank-wide.']},
    {img:'pj-02.png',t:'The project profile and its seven figures',items:[2,16],
     say:['All eight profile fields the client drew, in their order.',
          'All seven figures are clickable and open a table site by site.',
          'The site rows always add back up to the project total.']},
    {img:'pj-03.png',t:'The three charts',items:[17,19],
     say:['User mix uses the client’s own three-way split.',
          'The curve is cumulative, so it ends at the project’s declared total.',
          'The bottom chart shows why one site declares everything and another almost nothing.']},
   ],
   asks:[
    {q:'Which SharePoint site belongs to which project?',
     b:'This is the one that matters. Nothing today connects a SharePoint site to a project number, so every figure on this dashboard is a placeholder — the layout is right, the numbers are invented.',
     n:'Is there a list anywhere, even a spreadsheet someone keeps by hand? If sites are named to a pattern that includes the project number, that would work too.'},
    {q:'Where do the eight project details come from?',
     b:'Facility type, modality, country, status, effectivity and closing dates — these clearly live in an ADB project system, but that system has never been named in this work.',
     n:'Which system holds them, and who owns it? Once we know, we can ask for a feed.'},
   ]},

  {key:'fp',sheet:'4 Institutional File Plan',name:'Institutional File Plan',
   q:'Is the file plan actually being used?',
   slides:[
    {img:'fp-01.png',t:'The five categories',items:[1,11],
     say:['Five categories and a total, with the client’s own column names.',
          'The total row is checked against the bank-wide figures automatically.',
          'The department column is assigned, not measured. That is the gap on this dashboard.']},
    {img:'fp-02.png',t:'Inside one category',items:[12,19],
     say:['The client drew five screens. We built one screen with a category picker.',
          'Five figures at the top, then every top-level term underneath.',
          'Most used and least used terms are charted below the table.']},
    {img:'fp-03.png',t:'Unused terms',items:[20,21],
     say:['Terms nobody is using, with when they were last touched and why they are flagged.',
          'This is the list you would work from when tidying the file plan.',
          'The figures are illustrative until we can measure real usage.']},
    {img:'fp-04.png',t:'Libraries created outside convention',items:[22,22],
     say:['Libraries that do not follow the standard pattern.',
          'To make this real we need the convention itself.',
          'Same question as on Department Insights.']},
    {img:'fp-05.png',t:'Requests waiting for a decision',items:[23,24],extra:[25,26],
     say:['New library, new term, and both kinds of deletion, in one place.',
          'Requestor, status and date submitted on every row.',
          'The last two rows are the gaps that govern this whole dashboard.']},
   ],
   asks:[
    {q:'Where does the official file plan live?',
     b:'Every term you can see on these screens is our own example. Nothing in this work has ever named the system that holds the real institutional file plan.',
     n:'Which system is it? If it is a document rather than a system, that is fine too — we just need to know.'},
    {q:'How do we know a library is using a term?',
     b:'This is the technical heart of the problem, put simply: the system knows which library a document sits in, but nothing says which file plan category that library belongs to. Without that link, no figure on this dashboard can be measured.',
     n:'Is that mapping recorded anywhere? If not, is there a rule we could apply — for example, does the library name tell you the category?'},
    {q:'Where are new term and new library requests raised?',
     b:'The screen shows requests waiting for a decision. We invented them, because we do not know where real ones are submitted.',
     n:'When someone wants a new term or a new library, what do they do today?'},
    {q:'Should the screen say what is missing?',
     b:'Until yesterday this dashboard carried a notice explaining that the figures were placeholders. It has been taken off.',
     n:'For the workshop — do you want that notice back on screen, or is it enough that it is tracked in the checklist?'},
   ]},

  {key:'rd',sheet:'5 Retention and Disposal',name:'Retention and Disposal',
   q:'What must be kept forever, and what is coming up for disposal?',
   seq:{rel:'Disposal release',
    head:'Retention works today. Disposal is not in the system yet.',
    now:['Retention labels are being applied to records right now, and we can read them.',
         'We can show what is permanent, what is temporary, and when each item falls due.',
         'That half of this dashboard is real and working.'],
    blocked:['There is no screen in EDRMS where somebody approves a disposal.',
             'There is no field anywhere that records approved, declined or extended.',
             'So nothing can tell the report that a disposal actually happened.'],
    ask:'We propose building the retention half now, and the disposal half once the Disposal release ships. The screens are already drawn and waiting — when the feature exists, they fill in.',
    count:14},
   slides:[
    {img:'rd-01.png',t:'Permanent against temporary',items:[1,12],
     say:['Six figures: sites, libraries and records, split permanent and temporary.',
          'This is the closest match of the six to something we already had built.',
          'The summary table the client drew on slide 44 was taken off. That needs your view.']},
    {img:'rd-02.png',t:'Permanent retention',items:[13,18],
     say:['Everything that must be kept indefinitely, department by department.',
          'All five columns the client asked for are here.',
          'One column is missing: the file plan term.']},
    {img:'rd-03.png',t:'Temporary retention',items:[19,26],
     say:['Same shape, for records with an end date.',
          'The retention filter lets you look at just the seven-year records, or just the ten-year.',
          'What we cannot show is anything that has already been disposed of.']},
    {img:'rd-04.png',t:'Retention labels',items:[27,27],
     say:['Every declared record grouped by the label actually applied to it.',
          'This comes from real data — it is one of the most solid panels in the report.',
          'It is also a good check: labels nobody expected will show up here.']},
   ],
   asks:[
    {q:'Can we agree the disposal half follows the Disposal release?',
     b:'This is not a data problem we can solve by looking harder. Disposal is not built in EDRMS yet — there is no approval screen and no field to record an outcome. Fourteen items across three dashboards are waiting on that one release.',
     n:'We build the screens now so they are ready, and switch them on when Disposal ships. Nothing is wasted and nothing is invented in the meantime.'},
    {q:'Do you still want the slide 44 summary table?',
     b:'Your slide 44 had a table across the top with six columns. It was taken out of the prototype because most of its columns repeat what the screens below already show.',
     n:'Do you want it back, or is the current layout clearer? Your call — we can put it back easily.'},
    {q:'Should retention be shown per file plan term?',
     b:'Slides 45 and 46 both start with a “Term (top level)” column. We cannot fill it for the same reason as the file plan dashboard — nothing links a record to a term.',
     n:'If the file plan question gets answered, this fills itself in. Same root cause.'},
   ]},

  {key:'ra',sheet:'6 Records and Archive Holdings',name:'Records and Archive Holdings',
   q:'What is in the physical archive, and what is moving in and out?',
   seq:{rel:'Physical Records release',
    head:'This one is about paper, and paper comes after Utilization.',
    now:['One figure here is real: how many declared records are marked as having a paper copy.',
         'That is the bridge between this report and what RAC physically holds.',
         'The layout answers every column and every indicator you drew.'],
    blocked:['Boxes, folders, rooms, requests and retrievals live in the physical world.',
             'The systems that will track them are part of the Physical Records work, which comes after Utilization.',
             'Nothing we can reach today holds any of it, so every figure on this screen is invented.'],
    ask:'We propose treating this dashboard as a Physical Records deliverable rather than a Utilization one. Showing it now would mean showing you numbers we made up, and those have a way of being quoted back as real.',
    count:26},
   slides:[
    {img:'ra-01.png',t:'What we can and cannot see',items:[1,2],
     say:['One figure here is real: the count of records with a paper counterpart.',
          'Everything else on this dashboard is a placeholder.',
          'This is the dashboard with the least data behind it, and the most to discuss.']},
    {img:'ra-02.png',t:'Storage',items:[3,13],
     say:['All seven columns from your slide 68, with your own wording.',
          'Three locations: Archives Room, Records Center, Offsite Storage.',
          'Below it, storage activity by department and how full each room is.']},
    {img:'ra-03.png',t:'Retrieval',items:[14,20],
     say:['All seven columns from your slide 69.',
          'Status uses your own three words: Loan, Return to owner, For Disposal.',
          'Everything on this table is invented, because we cannot reach the request system.']},
    {img:'ra-04.png',t:'Activity, disposal and capacity',items:[21,26],
     say:['Retrieval by department, what was disposed, and how much space that freed.',
          'The layout answers every indicator you asked for.',
          'None of it is measured yet. That is what the questions slide is for.']},
   ],
   asks:[
    {q:'Can we agree this dashboard follows the Physical Records release?',
     b:'Everything on it — boxes, folders, rooms, requests — is physical, and the systems that will hold that information come with the Physical Records work, after Utilization. Building it now means inventing all 26 figures.',
     n:'Keep the layout as the agreed specification, sign it off today if you are happy with it, and build it when the physical side has real sources behind it.'},
    {q:'When someone asks RAC for a box, where does that go?',
     b:'Your slide 67 mentions eServe. Nothing in this work has ever reached it. Even after the Physical release we will need this answered.',
     n:'Can we see what eServe holds, and who would we ask for access? Worth starting the conversation now so it is not the thing that delays the physical build later.'},
    {q:'What does RAC actually keep today, and where?',
     b:'Boxes, folders, which room they are in, how full each room is. It may live in a spreadsheet, or on paper, or in somebody\u2019s head.',
     n:'Whatever the answer, it is the starting point for the physical work. A spreadsheet is a perfectly good answer.'},
   ]},
 ]
};
