"""Column definitions for the four Utilization Report tables.

Written to the conventions of Database_Design_12.03_5.xlsx:
  - PostgreSQL field types, not friendly names (uuid, text, boolean,
    timestamp with time zone), because that is what the existing sheets use
  - descriptions explain jargon inline, the way the FavoriteLocations sheet
    does: "The User Principal Name, meaning the sign-in email address, of..."
  - REFERENCE TABLES names the table a column joins to

Each column is (name, pg_type, description, values, sample, reference, remarks).
"""

RELEASE = "2026.4"
DECL = "All"          # these tables are not declaration-type specific

# --------------------------------------------------------------------------
T1 = [
 ("Id", "uuid",
  "Primary key. Uniquely identifies each row of the snapshot. Regenerated on every refresh, because the whole table is replaced rather than updated in place.",
  "System generated", "3f2a91c4-7b18-4d0e-9a52-c6f0b81c4d2e", "", ""),
 ("SnapshotDate", "date",
  "The date the refresh job captured this data. The same value appears on every row of a single run, and it is what the Data as of line prints at the top of every dashboard.",
  "System generated", "2026-07-27", "",
  "NEW. One value per run. A dashboard is only as current as this date."),
 ("DocumentId", "text",
  "The SharePoint Document ID, meaning the identifier SharePoint assigns to a document and keeps through a rename or a move.",
  "SharePoint Document ID", "1000-52341", "",
  "Nullable, which is why it is not the row identity. See ListId and ItemId."),
 ("Title", "text", "The filename of the document, including its extension.",
  "Free text", "Board Paper Q2.pdf", "", ""),
 ("DocumentUrl", "text",
  "The full web address of the document, so a reader can click through from the report to the file itself.",
  "Absolute URL", "https://adb.sharepoint.com/sites/edrms-cwrd/AnnualMeet/Board Paper Q2.pdf", "",
  "NEW. Assembled at load time from SiteUrl, LibraryUrl, FolderPath and Title. Not stored anywhere today."),
 ("FileType", "text", "The file extension in lower case, taken from the filename.",
  "Free text", "pdf", "", "Flattened out of the FileMeta JSON, keeping the key name."),
 ("FormatGroup", "text",
  "The format family the report groups by. Derived from FileType using a mapping list, so that doc and docx both count as Word.",
  "PDF / Word / Excel / PowerPoint / Email / Image files / Video files / All other formats",
  "PDF", "",
  "NEW. Derived. RAC signs off the extension to group mapping once; anything unrecognised falls into All other formats."),
 ("FileSize", "bigint",
  "The size of the file in bytes. Held in bytes rather than megabytes so nothing is rounded before it is totalled.",
  "System generated", "2516582", "",
  "NEW KEY on FileMeta. Every storage figure depends on it. Microsoft Graph returns it on every item, so the scan gets it at no extra cost."),
 ("FileCreatedDate", "timestamp with time zone",
  "The date and time the file itself was created, which is not the same as the date it was declared a record.",
  "System generated", "2026-03-12 09:14:00+00", "",
  "The date range on the Total Documents panel reads this column."),
 ("FileModifiedDate", "timestamp with time zone",
  "The date and time the file itself was last changed.",
  "System generated", "2026-06-04 16:02:00+00", "",
  "NEW. Named this way because ModifiedDate in Records means when the record row changed, not the file."),
 ("FolderPath", "text",
  "The folder path inside the library, so documents can be separated by folder within one library.",
  "Server relative path", "/2026/Q2/Board", "", ""),
 ("LibraryName", "text", "The display name of the document library holding the file.",
  "Free text", "Annual Meetings", "", "The deepest level of the drill down."),
 ("LibraryUrl", "text", "The web address of the library, for click through.",
  "Server relative URL", "/sites/edrms-cwrd/AnnualMeet", "", ""),
 ("LibraryLastActivityDate", "date",
  "The date anything in the library last changed. Used to judge whether a library is still in use.",
  "System generated", "2026-07-22", "",
  "NEW. Microsoft Graph returns it as lastModifiedDateTime on the drive, from the same call that supplies LibraryCount. Repeated on every document row of that library."),
 ("ListId", "uuid",
  "The GUID, meaning the system generated identifier, of the SharePoint library. Libraries can be renamed but this does not change, so every library figure groups on it.",
  "SharePoint list GUID", "a869c724-ac4f-4144-8526-69b5aeef3a68", "",
  "Verified to match SharePoint's own list GUID, so the join to Graph is safe."),
 ("ItemId", "integer",
  "The item number SharePoint assigns within a library. Unique inside one library, not across libraries.",
  "System generated", "203", "",
  "With ListId this identifies exactly one item. Together they are the identity of a row."),
 ("ADBLibraryCategory", "text",
  "The category the library belongs to, used to group records by classification.",
  "Common Document Library / Procurement / and the other values in the mapping list",
  "Common Document Library", "Retention Label Mapping list",
  "ADBMeta is empty. The same value is maintained today as Library Type in the Retention Label Mapping list."),
 ("SiteName", "text", "The display name of the SharePoint site holding the file.",
  "Free text", "EDRMS CWRD", "Site Activity Table", ""),
 ("SiteUrl", "text",
  "The web address of the site holding the file. This is the column that joins a document to its site.",
  "Absolute URL", "https://adb.sharepoint.com/sites/edrms-cwrd", "Site Activity Table",
  "The join key behind every department figure. Every existing row already carries it."),
 ("SiteCreatedDate", "date",
  "The date the SharePoint site was created. Copied from the Site Activity Table so a document can be filtered by the age of its site without a join.",
  "System generated", "2026-01-18", "Site Activity Table", "NEW."),
 ("IsEdrmsCompliant", "boolean",
  "Whether the site holding this document is an EDRMS compliant site, meaning it has the Declare as Record button.",
  "true / false", "true", "Site Activity Table",
  "NEW. Determined by whether the EDRMS app is installed on the site. Defines the population of this whole table."),
 ("ADBDepartmentOwner", "text",
  "The department that owns the site holding this document. Inherited from the site rather than set on each document.",
  "Values from the Department term set", "CWRD", "Site Activity Table",
  "GAP. The SharePoint column exists and is empty on every row. Arrives from the RAC site mapping, loaded onto the site and inherited through SiteUrl."),
 ("IsDeclaredRecord", "boolean",
  "Whether this document has been formally declared a record. This is the single most important column in the report, because it separates the numerator from the denominator in every rate.",
  "true / false", "true", "",
  "NEW but free. Derived at load: true where the document is present in Records, false where the scan found it and Records does not."),
 ("CreatedDate", "timestamp with time zone",
  "The date and time the user declared the file as a record. Blank for a document that has never been declared.",
  "System generated", "2026-03-12 09:14:00+00", "",
  "Every declaration date filter reads this column. Not the file's own creation date."),
 ("CreatedBy", "text",
  "The User Principal Name, meaning the sign-in email address, of the person who declared the record.",
  "Valid ADB UPN", "jperez@adb.org", "", ""),
 ("DeclarationType", "integer",
  "Whether the record was declared individually or through a centralised process, held as a numeric code.",
  "System generated", "1", "",
  "Deployed today as an integer. The code to label mapping needs confirming with the development team."),
 ("HasPhysical", "boolean",
  "Whether a physical paper counterpart of this record exists.",
  "true / false", "false", "",
  "Blank rather than false for undeclared documents, since neither answer is known for them."),
 ("PhysicalCounterpartRetention", "text",
  "The retention that applies to the physical copy, maintained per library rather than per document.",
  "Long Term / Permanent", "Long Term", "Retention Label Mapping list", ""),
 ("EDRMSRetentionLabel", "text",
  "The retention label applied to the file, which is what determines how long it is kept.",
  "Values from the Purview file plan", "10 years after declaration", "",
  "A record with no label has no disposal date and cannot be scheduled at all."),
 ("EDRMSDuration", "text",
  "The length of the retention period attached to the label.",
  "Free text", "10", "",
  "Stored as text rather than a number so it can hold Permanent alongside 10. Cast before doing arithmetic on it."),
 ("EDRMSRetentionLabelApplied", "timestamp with time zone",
  "The date and time the retention label was applied to the file.",
  "System generated", "2026-03-12 09:20:00+00", "",
  "Never use this to date a declaration. A label can be applied to a document that was never declared."),
 ("EDRMSDueDateForDisposal", "date",
  "The date the record becomes due for disposal, computed as the label applied date plus the duration.",
  "System generated", "2036-03-12", "",
  "Already computed in the source database. Records due for disposal is a count over this column and needs nothing new."),
 ("RetentionStatus", "text",
  "The retention classification derived from the duration.",
  "Values maintained in EDRMSMasters", "Active", "EDRMSMasters", ""),
 ("SensitivityLabelName", "text",
  "The sensitivity label applied to the file, such as Internal or Confidential.",
  "Values from the DRM Classification Information term set", "Internal", "",
  "Not on any current dashboard. Carried because it is free and the obvious basis for a protection view."),
 ("IsDeleted", "boolean",
  "Soft delete flag. Every count on every dashboard excludes rows where this is true.",
  "true / false", "false", "",
  "For undeclared documents, absence from the next scan is the delete signal."),
 ("RowLoadedDate", "timestamp with time zone",
  "The date and time this row was last written by the refresh job.",
  "System generated", "2026-07-27 06:00:00+00", "",
  "NEW. Operational only. Lets a failed or partial refresh be spotted."),
]

# --------------------------------------------------------------------------
T2 = [
 ("Id", "uuid", "Primary key. Uniquely identifies each site row of the snapshot.",
  "System generated", "8c1d47b2-93ae-4f60-b1d5-2e7a6f0c9d31", "", ""),
 ("SnapshotDate", "date",
  "The date the refresh job captured this data. The same value on every row of a run.",
  "System generated", "2026-07-27", "", "NEW."),
 ("SiteUrl", "text",
  "The web address of the site. This is the column that joins this table to the Utilization Report Table.",
  "Absolute URL", "https://adb.sharepoint.com/sites/edrms-cwrd", "Utilization Report Table",
  "Ask the development team whether the site GUID is also available. A URL can change; a GUID cannot."),
 ("SiteName", "text", "The display name of the site.",
  "Free text", "EDRMS CWRD", "", ""),
 ("SiteCreatedDate", "date", "The date the SharePoint site was created.",
  "System generated", "2026-01-18", "",
  "NEW. Microsoft Graph returns it as createdDateTime on every site."),
 ("IsEdrmsCompliant", "boolean",
  "Whether this is an EDRMS compliant site, meaning the Declare as Record button is available in it.",
  "true / false", "true", "",
  "NEW. Determined by whether the EDRMS app is installed on the site. Product ID {B255A2AF-7F63-4A30-966A-5D5FD99F97D7}."),
 ("ADBDepartmentOwner", "text", "The department that owns this site.",
  "Values from the Department term set", "CWRD", "",
  "GAP. Nothing in SharePoint supplies it. Loaded once from the RAC site mapping, roughly 1,057 rows, and inherited by every document in the site."),
 ("SiteVisits7", "integer", "The number of page views in the site over the last 7 days.",
  "System generated", "412", "", "NEW. From the Microsoft 365 SharePoint site usage report."),
 ("SiteVisits30", "integer", "The number of page views in the site over the last 30 days.",
  "System generated", "4812", "", "NEW. Same report at period='D30'."),
 ("SiteVisits90", "integer", "The number of page views in the site over the last 90 days.",
  "System generated", "13240", "", "NEW. Same report at period='D90'."),
 ("UniqueViewers7", "integer",
  "The number of distinct people who opened something in the site over the last 7 days.",
  "System generated", "38", "",
  "NEW. Do not sum this across sites to count people: anyone working in three sites is counted three times."),
 ("UniqueViewers30", "integer",
  "The number of distinct people who opened something in the site over the last 30 days.",
  "System generated", "122", "",
  "NEW. Microsoft returns no equivalent at 90 days, which is why there is no UniqueViewers90 column."),
 ("LibraryCount", "integer", "The number of document libraries in the site.",
  "System generated", "12", "",
  "NEW. Microsoft Graph, GET /sites/{id}/drives, counted."),
 ("LastActivityDate", "date", "The date anything in the site was last touched.",
  "System generated", "2026-07-24", "",
  "NEW. A site with no activity for 90 days is reported as inactive. The threshold is applied in the report, not stored here."),
 ("StorageUsed", "bigint", "The storage consumed by the site, in bytes.",
  "System generated", "13636370432", "",
  "NEW. Includes version history, so it reads higher than the sum of FileSize. Expected, not an error."),
 ("SiteOwner", "text",
  "The User Principal Name of the primary site administrator, meaning who to contact about a site that has gone quiet.",
  "Valid ADB UPN", "jperez@adb.org", "",
  "NEW. Measured at 1,683 of 1,702 sites carrying one."),
 ("ProjectEndDate", "date", "The project end date recorded against the site.",
  "System generated", "2027-12-31", "ADBSites",
  "Already exists and is populated. The obvious basis for a site closure view."),
 ("IsDeleted", "boolean", "Soft delete flag. Closed sites stay in the table so historical figures do not change.",
  "true / false", "false", "",
  "A site missing from the next export is the delete signal."),
 ("RowLoadedDate", "timestamp with time zone", "The date and time this row was last written.",
  "System generated", "2026-07-27 06:00:00+00", "", "NEW. Operational only."),
]

# --------------------------------------------------------------------------
T3 = [
 ("Id", "uuid", "Primary key. Uniquely identifies each person row of the snapshot.",
  "System generated", "b47f2e0a-5c93-41d8-8a16-7f3d05e6b8c2", "", ""),
 ("SnapshotDate", "date", "The date the refresh job captured this data.",
  "System generated", "2026-07-27", "", "NEW."),
 ("UserPrincipalName", "text",
  "The User Principal Name, meaning the sign-in email address, of a person who used SharePoint in the window. Counting distinct values of this column is the entire purpose of the table.",
  "Valid ADB UPN", "jperez@adb.org", "",
  "NEW. This is why the table exists: people cannot be counted from a table of sites."),
 ("DisplayName", "text", "The person's display name, for readability when the list is inspected.",
  "Free text", "J Perez", "", "NEW."),
 ("LastActivityDate", "date", "The date of the person's most recent SharePoint activity.",
  "System generated", "2026-07-24", "",
  "NEW. Filter on this to count active users over 7 or 30 days."),
 ("ViewedOrEditedFileCount", "integer",
  "The number of files the person viewed or edited during the window.",
  "System generated", "42", "",
  "NEW. Separates heavy users from someone who opened one document, and is the obvious basis for an adoption view."),
 ("RowLoadedDate", "timestamp with time zone", "The date and time this row was last written.",
  "System generated", "2026-07-27 06:00:00+00", "", "NEW. Operational only."),
]

# --------------------------------------------------------------------------
T4 = [
 ("Id", "uuid", "Primary key. Uniquely identifies each term row of the snapshot.",
  "System generated", "e05b8c31-7d42-4a96-b3f8-1c9e4a70d582", "", ""),
 ("SnapshotDate", "date", "The date the refresh job captured this data.",
  "System generated", "2026-07-27", "", "NEW."),
 ("TermId", "uuid",
  "The GUID, meaning the system generated identifier, of the term. Stable across a rename, so counts do not jump when somebody edits a label.",
  "Term store GUID", "6f2c1a48-9b30-4e75-8d21-c4a7e0f39a41", "", "NEW."),
 ("TermName", "text", "The label of the term as it appears in the term store.",
  "Free text", "Procurement Planning", "", "NEW."),
 ("TermSetName", "text", "The term set the term belongs to.",
  "Free text", "Procurement", "", "NEW."),
 ("CategoryName", "text",
  "The top level term group the term sits under, which is what the report groups by.",
  "Values from the term store groups", "ADB", "",
  "NEW. UNVERIFIED. The five categories in the requirement do not exist in the tenant's term store. See the Structure sheet."),
 ("Depth", "integer",
  "How many levels below the term set the term sits. A term directly under a term set is 1.",
  "System generated", "3", "",
  "NEW. Recorded while walking the tree at no extra cost, and it answers how deep the plan actually runs."),
 ("RowLoadedDate", "timestamp with time zone", "The date and time this row was last written.",
  "System generated", "2026-07-27 06:00:00+00", "", "NEW. Operational only."),
]

TABLES = [
 ("1 UtilizationReport", "UTILIZATION REPORT TABLE",
  "One row per document held in an EDRMS compliant site, declared or not. About 3.47 million rows, replaced in full at each weekly refresh. "
  "The undeclared documents are the point: without them there is no denominator and therefore no declaration rate.",
  T1),
 ("2 SiteActivity", "SITE ACTIVITY TABLE",
  "One row per SharePoint site. About 1,057 rows. Exists for the two things a document level table cannot do: count a site that holds no documents, "
  "and hold visit and viewer counts that are measured per site and would be nonsense repeated on every document row.",
  T2),
 ("3 UserActivity", "USER ACTIVITY TABLE",
  "One row per person who used SharePoint in the window. About 9,400 rows. Exists because Total EDRMS Users counts people, and a person working in "
  "three sites appears in three rows of the Site Activity Table, so summing UniqueViewers30 overstates headcount.",
  T3),
 ("4 FilePlan", "FILE PLAN TABLE",
  "One row per term in the institutional file plan. Exists because the file plan is the taxonomy that classifies content, so its terms are neither "
  "documents nor sites nor people and none of the other three tables can hold them.",
  T4),
]
